#!/bin/bash
HERE=$(pwd)

if [[ "$1" == "-p" ]];then
	CSCOPE=pycscope
	ARGS="-i $HERE/cscope/cscope.files"
	LNX=$HERE/$2
else
	CSCOPE=cscope
	ARGS=" -b -q -k"
	LNX=$HERE/$1
fi


echo "Using $CSCOPE on this source code"

if ! [[ -d $HERE/cscope ]];then
   mkdir -p $HERE/cscope
   fi

if [[ "$CSCOPE" == "cscope" ]];then
	find  $LNX                                                            \
	-path "$LNX/tmp*" -prune -o                                           \
	-path "$LNX/scripts*" -prune -o                                       \
	-name "*.[chxsS]" -print > $HERE/cscope/cscope.files

	find  $LNX                                                            \
	-path "$LNX/tmp*" -prune -o                                           \
	-path "$LNX/scripts*" -prune -o                                       \
	-name "*.[chxsS][c]" -print >> $HERE/cscope/cscope.files
else
	find $LNX -name "*.py" -print > $HERE/cscope/cscope.files
fi

cd $HERE/cscope
$CSCOPE $ARGS
